In [4]:
from splusdata.features.g_star import ClassifyObj
import pandas as pd
from astropy.table import Table
from pathlib import Path
ROOT_PATH = Path("star-class")

In [7]:
tab = pd.read_csv(ROOT_PATH / 'table-version-incom.csv')
tab.columns

Index(['Unnamed: 0', 'Field', 'ID', 'RA', 'DEC', 'FWHM', 'FWHM_n', 'A', 'B',
       'ISOarea', 'KRON_RADIUS', 'nDet_PStotal', 'PhotoFlagDet', 'u_PStotal',
       'J0378_PStotal', 'J0395_PStotal', 'J0410_PStotal', 'J0430_PStotal',
       'g_PStotal', 'J0515_PStotal', 'r_PStotal', 'J0660_PStotal', 'i_PStotal',
       'J0861_PStotal', 'z_PStotal', 'e_u_PStotal', 'e_J0378_PStotal',
       'e_J0395_PStotal', 'e_J0410_PStotal', 'e_J0430_PStotal', 'e_g_PStotal',
       'e_J0515_PStotal', 'e_r_PStotal', 'e_J0660_PStotal', 'e_i_PStotal',
       'e_J0861_PStotal', 'e_z_PStotal', 'u_iso', 'J0378_iso', 'J0395_iso',
       'J0410_iso', 'J0430_iso', 'g_iso', 'J0515_iso', 'r_iso', 'J0660_iso',
       'i_iso', 'J0861_iso', 'z_iso', 'e_u_iso', 'e_J0378_iso', 'e_J0395_iso',
       'e_J0410_iso', 'e_J0430_iso', 'e_g_iso', 'e_J0515_iso', 'e_r_iso',
       'e_J0660_iso', 'e_i_iso', 'e_J0861_iso', 'e_z_iso'],
      dtype='object')

In [8]:
clf = ClassifyObj(tab, model="RF16", return_prob = True, match_irsa=False)

Loading model
Note that this function assumes that the input data were previously extinction corrected. Starting classification...
Calculating probabilities...
Finished process.

In [11]:
clf.results

      CLASS  PROB_QSO  PROB_STAR  PROB_GAL
0       1.0     0.310      0.680      0.01
1       1.0     0.370      0.630      0.00
2       0.0     0.450      0.270      0.28
3       1.0     0.265      0.595      0.14
4       0.0     0.500      0.470      0.03
...     ...       ...        ...       ...
5118    2.0     0.000      0.090      0.91
5119    2.0     0.150      0.230      0.62
5120    2.0     0.260      0.100      0.64
5121    1.0     0.270      0.580      0.15
5122    2.0     0.270      0.260      0.47

[5123 rows x 4 columns]

In [21]:
df = clf.results

In [25]:
tab_f = pd.concat([tab, df])

In [26]:
tab_f

,Unnamed: 0,Field,ID,RA,DEC,FWHM,FWHM_n,A,B,ISOarea,...,e_J0515_iso,e_r_iso,e_J0660_iso,e_i_iso,e_J0861_iso,e_z_iso,CLASS,PROB_QSO,PROB_STAR,PROB_GAL
0,0.0,HYDRA-0142,iDR3.HYDRA-0142.105190,159.308587,-42.785442,1.944774,0.913932,1.291544,1.157371,14.0,...,0.105923,0.034313,0.019371,0.045118,0.086663,0.063104,NaN,NaN,NaN,NaN
1,1.0,HYDRA-0142,iDR3.HYDRA-0142.119196,160.010326,-42.640277,1.965757,0.923793,1.323208,1.124100,18.0,...,0.112199,0.030642,0.019945,0.036961,0.070845,0.069806,NaN,NaN,NaN,NaN
2,2.0,HYDRA-0143,iDR3.HYDRA-0143.000397,161.845557,-43.913593,2.927601,1.225450,1.439430,1.286659,17.0,...,0.300881,0.052679,0.040779,0.060439,0.127335,0.092450,NaN,NaN,NaN,NaN
3,3.0,HYDRA-0143,iDR3.HYDRA-0143.037864,162.162826,-43.455750,2.677275,1.120667,1.935881,1.341528,20.0,...,0.307178,0.064497,0.027417,0.052629,0.118529,0.078855,NaN,NaN,NaN,NaN
4,4.0,HYDRA-0143,iDR3.HYDRA-0143.064140,162.626493,-43.132023,2.177529,0.911481,1.291501,1.211863,14.0,...,0.648517,0.064743,0.034993,0.055616,0.101865,0.099342,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.00,0.09,0.91
5119,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.15,0.23,0.62
5120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.26,0.10,0.64
5121,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.27,0.58,0.15
5122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.27,0.26,0.47